name: Build and Publish Docker Image

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
      PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Get version from Cargo.toml
        id: cargo-version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -n1 | sed 's/version = "//;s/"//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Tag commit with version (if not exists)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          TAG="v${{ steps.cargo-version.outputs.version }}"
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG"; then
            echo "Tag $TAG already exists on remote. Skipping tag creation and push."
          else
            git tag $TAG
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $TAG
          fi

      - name: Build release binary
        run: cargo build --release

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/notification-api:${{ steps.cargo-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/notification-api:latest
          build-args: |
            PUSHOVER_TOKEN=${{ secrets.PUSHOVER_TOKEN }}
            PUSHOVER_USER=${{ secrets.PUSHOVER_USER }}

      - name: Load .env for non-sensitive config
        run: |
          set -a
          source .env
          set +a
